/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const KayakDesign = IDL.Record({
  'manufacturer' : IDL.Text,
  'externalLink' : IDL.Text,
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
  'designYear' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addKayakDesign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllKayakDesigns' : IDL.Func([], [IDL.Vec(KayakDesign)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const KayakDesign = IDL.Record({
    'manufacturer' : IDL.Text,
    'externalLink' : IDL.Text,
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
    'designYear' : IDL.Nat,
  });
  
  return IDL.Service({
    'addKayakDesign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllKayakDesigns' : IDL.Func([], [IDL.Vec(KayakDesign)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };